
# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# List of jobs
jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
      AWS_ACCESS_KEY_ID = ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION = ${{ secrets.AWS_REGION }}
    steps:
      - name: git clone
        uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: npm build
        run: npm run build

      - name: Deploy
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET }}
          invalidation: / *