name: Example workflow for S3 Deploy
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install

      - name: Generate Environment
        run : |
          echo "REACT_APP_HOST_NAME=$REACT_APP_HOST_NAME" >> .env.production
        env :
          REACT_APP_HOST_NAME: ${{ secrets.REACT_APP_HOST_NAME }}
      - name: Build
        run: npm run build

      - name: S3 Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 cp \
          --recursive \
          --region ap-northeast-2 \
          build s3://weshareus

      - name: Invalidate CloudFront Cache
        uses: chetan/invalidate-cloudfront-action@master
        env:
          AWS_DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: '/index.html'
        continue-on-error: true